### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Holzhaus** [philj56/tofi#203]
Getting the following segfault when running `tofi` without any arguments.

````
Program terminated with signal SIGSEGV, Segmentation fault.
#0  wl_proxy_get_version (proxy=0x0) at ../wayland-1.23.1/src/wayland-client.c:2317
2317		return proxy->version;
>>> bt
#0  wl_proxy_get_version (proxy=0x0) at ../wayland-1.23.1/src/wayland-client.c:2317
#1  0x0000564775bd469d in ?? ()
#2  0x00007ea12cce9e08 in __libc_start_call_main (main=main@entry=0x564775bd4040, argc=argc@entry=1, argv=argv@entry=0x7ffd36c637e8) at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x00007ea12cce9ecc in __libc_start_main_impl (main=0x564775bd4040, argc=1, argv=0x7ffd36c637e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffd36c637d8) at ../csu/libc-start.c:360
#4  0x0000564775bc9625 in ?? ()
```

**Comment by kaushiksahu18** [comment]
## same

❯  tofi
zsh: segmentation fault (core dumped)  tofi
